Revert "Reland "Do not use StringIO""
This reverts commit baa5e3d3e2c80d012302e46d5dadc22c8f222f75.

Reason for revert: caused crbug/1187730

Original change's description:
> Reland "Do not use StringIO"
>
> This reverts commit 690b1d3241d9ee460f2cb2d279d2db7a7afca368.
>
> Reason for revert: will manually roll catapult
>
> Original change's description:
> > Revert "Do not use StringIO"
> >
> > This reverts commit ee38b50ccb4f754577aed5b42bbaa406867c598f.
> >
> > Reason for revert: Causing the catapult roll to fail: https://ci.chromium.org/ui/p/chromium/builders/try/android-binary-size/750590/overview
> >
> >   File "/b/s/w/ir/cache/builder/src/third_party/catapult/devil/devil/utils/cmd_helper.py", line 18, in <module>
> >   import six
> >   ImportError: No module named six
> >
> >
> > Original change's description:
> > > Do not use StringIO
> > >
> > > In attempt to make catapult work under py3.
> > >
> > > Bug: chromium:1183514
> > > Change-Id: I4d53628c2571cb98872350f372433f3c9104f65f
> > > Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2726534
> > > Commit-Queue: Weizhong Xia <weizhong@google.com>
> > > Reviewed-by: Ben Pastene <bpastene@chromium.org>
> > > Reviewed-by: Dirk Pranke <dpranke@google.com>
> >
> > Bug: chromium:1183514
> > Change-Id: Iebcf1d1eb7ac263df9a5c683673668f0005e3adc
> > No-Presubmit: true
> > No-Tree-Checks: true
> > No-Try: true
> > Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2739458
> > Auto-Submit: Sami Kyöstilä <skyostil@chromium.org>
> > Reviewed-by: Sami Kyöstilä <skyostil@chromium.org>
> > Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
>
> Bug: chromium:1183514
> Change-Id: Ie234ed686d86bf9b4bc504e77c719763f3438db5
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2738955
> Reviewed-by: Dirk Pranke <dpranke@google.com>
> Reviewed-by: Dean Berris <dberris@chromium.org>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Commit-Queue: Weizhong Xia <weizhong@google.com>

Bug: chromium:1183514
Change-Id: I6709eb140e41f097f3c86da11cb58449c33bfac2
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2757317
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Weizhong Xia <weizhong@google.com>
Reviewed-by: Dirk Pranke <dpranke@google.com>