Revert "Devil: string constants for ABIs"
This reverts commit 114ad6af189bb1810797f98be02a9ca2b5a621bf.

Reason for revert: See error at https://chromium-swarm.appspot.com/task?id=42970c67153a7010&refresh=10&show_raw=1

Traceback (most recent call last):
  File "/b/swarming/w/ir/build/android/test_runner.py", line 40, in <module>
    from pylib.base import environment_factory
  File "/b/swarming/w/ir/build/android/pylib/base/environment_factory.py", line 6, in <module>
    from pylib.local.device import local_device_environment
  File "/b/swarming/w/ir/build/android/pylib/local/device/local_device_environment.py", line 17, in <module>
    from devil.android import device_utils
  File "/b/swarming/w/ir/third_party/catapult/devil/devil/android/device_utils.py", line 33, in <module>
    from devil.android import apk_helper
  File "/b/swarming/w/ir/third_party/catapult/devil/devil/android/apk_helper.py", line 11, in <module>
    from devil.android.ndk import abis
ImportError: No module named ndk

Original change's description:
> Devil: string constants for ABIs
> 
> No change in logic.
> 
> This adds named constants for Android's supported ABIs. This
> intentionally omits mips (32 & 64) and armeabi because these are not
> supported by the NDK.
> 
> These might be nice to make sure arch-specific infra checks the correct
> ABI (reducing the possibility for typos).
> 
> This cross-links to the DeviceUtils methods which we can compare these
> constants against.
> 
> This also replaces string literals with the new constant values.
> 
> Test: git cl presubmit
> Change-Id: Iacc8c4d5763aac9f4e1f25b6bcf05c42a1bc4c08
> Reviewed-on: https://chromium-review.googlesource.com/c/1431852
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Commit-Queue: Nate Fischer <ntfschr@chromium.org>

TBR=ntfschr@chromium.org,jbudorick@chromium.org

Change-Id: I7aad39dde0c8af53aac1ba537a7c84f473a92703
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/1434218
Reviewed-by: Caleb Rouleau <crouleau@chromium.org>
Commit-Queue: Caleb Rouleau <crouleau@chromium.org>