Revert of [Telemetry] Try 2: Use check_call instead of Popen for osascript (patchset #2 id:20001 of https://codereview.chromium.org/1425453003/ )
Reason for revert:
Still throw exception:

  CalledProcessError: Command '['osascript', '-e', 'tell application "/b/build/slave/mac/build/src/out/Release/Chromium.app/Contents/MacOS/Chromium" to activate']' returned non-zero exit status 1
  Traceback (most recent call last):
    File "/b/build/slave/mac/build/src/tools/telemetry/telemetry/testing/browser_test_case.py", line 45, in setUpClass
      current_browser = browser_to_create.Create(options)
    File "/b/build/slave/mac/build/src/tools/telemetry/telemetry/internal/backends/chrome/desktop_browser_finder.py", line 67, in Create
      browser_backend, self._platform_backend, self._credentials_path)
    File "/b/build/slave/mac/build/src/tools/telemetry/telemetry/internal/browser/browser.py", line 55, in __init__
      self._browser_backend.Start()
    File "/b/build/slave/mac/build/src/tools/telemetry/telemetry/internal/backends/chrome/desktop_browser_backend.py", line 254, in Start
      self._executable)]) == 0, 5)
    File "/b/build/slave/mac/build/src/tools/telemetry/telemetry/core/util.py", line 75, in WaitFor
      res = condition()
    File "/b/build/slave/mac/build/src/tools/telemetry/telemetry/internal/backends/chrome/desktop_browser_backend.py", line 254, in <lambda>
      self._executable)]) == 0, 5)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '['osascript', '-e', 'tell application "/b/build/slave/mac/build/src/out/Release/Chromium.app/Contents/MacOS/Chromium" to activate']' returned non-zero exit status 1

Looks like check_call will raise CalledProcessError rather than return the exit code.

Original issue's description:
> [Telemetry] Try 2: Use check_call instead of Popen for osascript
>
> This didn't work properly last time because sometimes it can take a while
> before AppleScript can talk to the browser. Here, we use WaitFor to give
> everything a few seconds to catch up.
>
> BUG=538638
>
> Committed: https://crrev.com/ddbd6739dd693adbc85ecc5bafd400a6f59c3900
> Cr-Commit-Position: refs/heads/master@{#355916}

TBR=eakuefner@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=538638

Review URL: https://codereview.chromium.org/1423643003

Cr-Commit-Position: refs/heads/master@{#355921}