Fix TypeError in Anomaly.QueryAsync.
I noticed this TypeError in the logs when min_timestamp or max_timestamp is set.
TypeError: %d format: a number is required, not datetime.datetime

Change-Id: Ibbebe3fe0a39878563dcf794af71ba5b3a3a46e5
Reviewed-on: https://chromium-review.googlesource.com/1112905
Reviewed-by: Simon Hatch <simonhatch@chromium.org>
Commit-Queue: Ben Hayden <benjhayden@chromium.org>