Revert "Do not use StringIO"
This reverts commit ee38b50ccb4f754577aed5b42bbaa406867c598f.

Reason for revert: Causing the catapult roll to fail: https://ci.chromium.org/ui/p/chromium/builders/try/android-binary-size/750590/overview

  File "/b/s/w/ir/cache/builder/src/third_party/catapult/devil/devil/utils/cmd_helper.py", line 18, in <module>
  import six
  ImportError: No module named six


Original change's description:
> Do not use StringIO
>
> In attempt to make catapult work under py3.
>
> Bug: chromium:1183514
> Change-Id: I4d53628c2571cb98872350f372433f3c9104f65f
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2726534
> Commit-Queue: Weizhong Xia <weizhong@google.com>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Reviewed-by: Dirk Pranke <dpranke@google.com>

Bug: chromium:1183514
Change-Id: Iebcf1d1eb7ac263df9a5c683673668f0005e3adc
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2739458
Auto-Submit: Sami Kyöstilä <skyostil@chromium.org>
Reviewed-by: Sami Kyöstilä <skyostil@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>