Reland of [devil] Extract logging common behavior to its own module. (patchset #1 id:1 of https://codereview.chromium.org/2998833002/ )
Reason for revert:
Needs a src/-side change. Will manually handle the roll.

Original issue's description:
> Revert of [devil] Extract logging common behavior to its own module. (patchset #3 id:40001 of https://codereview.chromium.org/2972253002/ )
>
> Reason for revert:
> Appears to be blocking catapult roller. Tests are failing with, e.g.:
>
> Traceback (most recent call last):
>   File "/b/swarming/w/ir/build/android/test_runner.py", line 34, in <module>
>     from devil.utils import run_tests_helper
>   File "/b/swarming/w/ir/third_party/catapult/devil/devil/utils/run_tests_helper.py", line 10, in <module>
>     from devil.utils import logging_common
> ImportError: cannot import name logging_common
> [E2017-08-10T18:17:37.717840Z 31228 0 subcommand_run.go:333] Command completed with non-zero return code. {"returnCode":1}
> [I2017-08-10T18:17:37.718115Z 31228 0 main.go:349] Terminating.                                {"returnCode":1}
>
> https://build.chromium.org/p/tryserver.chromium.android/builders/android_n5x_swarming_rel/builds/240094
>
> Original issue's description:
> > [devil] Extract logging common behavior to its own module.
> >
> > Also deprecates the now-poorly-named run_tests_helper.py.
> >
> > Review-Url: https://codereview.chromium.org/2972253002
> > Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/d12f47164198cde6d62d47cb38c85e961480a9d7
>
> TBR=mikecase@chromium.org,bpastene@chromium.org,jbudorick@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
>
> Review-Url: https://codereview.chromium.org/2998833002
> Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/c150856156252a9aa2958c785b54412783af4d56

TBR=mikecase@chromium.org,bpastene@chromium.org,perezju@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/3000813002